### ISSUE TITLE
0x1802008DaD2d8F171e57D2653f20d48e25E22d13

### ISSUE THREAD

**Issue by anakinnet** [kulapio/EthereumWorkshop#2]

**Comment by totiz** [comment]
0xd0e688d1425c9e63e3d29b63890ca4e0ff494612954ca15d30dc0111051aceed

**Comment by totiz** [comment]
https://kovan.etherscan.io/tx/0xd0e688d1425c9e63e3d29b63890ca4e0ff494612954ca15d30dc0111051aceed

**Comment by guituja** [comment]
0xC0E9074B21832F7D480854043d3282A0B5A24F23

**Comment by Tpatiphan** [comment]
0xFc6BB7b29bE941409b4b90E380270D6f2c159968

**Comment by userkmitl** [comment]
0x74fab8e506451a6d4ebE6de5b71950f8d88Ef2cF

**Comment by Freezemeat** [comment]
0x2c31992b1b4fe9a1fC411460b4972Bd089502F15
